apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        version: ${APP_VERSION}
    spec:
      containers:
        - name: test-app
          image: ${IMAGE_NAME}:${APP_VERSION}
          ports:
            - containerPort: 5000