apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
      version: ${APP_VERSION}
  template:
    metadata:
      labels:
        app: test-app
        version: ${APP_VERSION}
    spec:
      containers:
        - name: test-app
          image: fasca22/test-app:${APP_VERSION}
          ports:
            - containerPort: 5000